name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - run: dotnet build src/Nvoip/Nvoip.csproj --configuration Release
      - run: dotnet build examples/Nvoip.Examples/Nvoip.Examples.csproj --configuration Release
